# Site settings
title: opencode.space
author: João Cerqueira
short_description: Experiences on software development and other random topics
description: >- # this means to ignore newlines until "baseurl:"
  Blog written by João Cerqueira that covers his experiences on software development
  and other random topics he may find worth sharing.

# Endpoint config
baseurl: ""
url: "https://opencode.space"
permalink: /:title

# Header menu
header_pages:
  - pages/about.md
  - pages/now.md

# Social & Contact
twitter_username: und0ck3d
github_username:  und0ck3d
email: joao@opencode.space

# Disqus
disqus:
  shortname: joaocrq

# Google Analytics
google_analytics: "UA-46694741-18"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
