# Site settings
title: opencode.space
author: João Cerqueira
description: >- # this means to ignore newlines until "baseurl:"
  Code snippets, tutorials, random notes and opinions
  from João Cerqueira.

# Endpoint config
baseurl: ""
url: "https://opencode.space"
permalink: /:title

# Header menu
header_pages:
  - pages/about.md
  - pages/now.md

# Social & Contact
twitter_username: und0ck3d
github_username:  und0ck3d
email: joao@opencode.space

# Disqus
disqus:
  shortname: joaocrq

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
